### ISSUE TITLE
The duckietown problem

### ISSUE THREAD

**Issue by zqzhang123** [YuehChuan/cmake-learn#1]
Hello. Thank you for helping with the problem yesterday about the duckietown. But there are some new problem today. When I try to roslaunch the joystick, I was told ros cannot launch the joy. Do you have any ideas about it?
![screenshot from 2017-11-07 18-20-23](https://user-images.githubusercontent.com/33078734/32525361-b91644a0-c3e9-11e7-9c52-f9df990ffb9b.png)
![screenshot from 2017-11-07 18-20-42](https://user-images.githubusercontent.com/33078734/32525362-b929d006-c3e9-11e7-8c47-60f4059b0af9.png)

**Comment by YuehChuan** [comment]
@zqzhang123  $ sudo apt install ros-kinetic-joy
it missed dependency.

**Comment by YuehChuan** [comment]
And it is not an issue relate to this repository, I will closed it for now. If you get any progress or still stock , please leave comment below.
